### ISSUE TITLE
Android Studio

### ISSUE THREAD

**Issue by ManenschijnJaap** [MyOrder/MyOrder-Payments-Android-SDK#1]
Hi there,

I'm trying to get this to work in an Android Studio project, but i can't get it right.
I can import the library and use it's classes.
However, as soon as i use any of the UI related parts (like a simple MyOrderLoginFragment), i get an immediate crash, saying:
java.lang.NoClassDefFoundError: nl.myorder.lib.R$layout

How can i get this to work?

Edit:
I did get it to work, by importing a module and then selecting the .project file.
However it would still give me errors on card_base.9.png.
Also, i had to wipe the entire Application tag in the AndroidManifest, as it would install 2 apps when running it on my phone.

**Comment by nhaarman** [comment]
PR #2 transforms the project to the Gradle system, so it can be easily used in modern applications.
